POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "My Product",
    "price": 1050
}

###

GET http://localhost:8000/products/378a60b4-0da1-4a56-9512-095bedc9a3c3 HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8000/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDQ5NjgxMTAsInN1YiI6ImZhYjZlMjIyLWYzMDItNDgzOC05NjcxLWZhMDk1YjhhYjQ4MiJ9.ZKVrbseCTAsRtCyovbQhcuq-bWiqtSKN4_XHo-oWNdM


###

PUT http://localhost:8000/products/378a60b4-0da1-4a56-9512-095bedc9a3c3 HTTP/1.1
Content-Type: application/json

{
  "name": "My Product Updated",
  "price": 1050
}

###

DELETE http://localhost:8000/products/388cf198-5413-4ece-88dd-dd546ef00cd9 HTTP/1.1
Content-Type: application/json